### ISSUE TITLE
Cloning private repository doesn't seem to work

### ISSUE THREAD

**Issue by kishanov** [someteam/acha#25]
v0.2.5, running local version using Java 8.

The repo is not public, hosted on bitbucket. 

Things that I tried:
* default options
* --private-key command line option with the path to ~/.ssh/id_rsa.pub
* both git@ and https:// URIs
* putting credentials (like username:password@uri) into repo URL

```
15:22:09.075 [ ERROR ] worker#3 : a.dispatcher - Repo analysis failed
org.eclipse.jgit.api.errors.TransportException: <some-private-repo-url>: USERAUTH fail
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125) ~[acha-uber-0.2.5.jar:na]
        at acha.git_parser$clone.invoke(git_parser.clj:43) ~[acha-uber-0.2.5.jar:na]
        at acha.git_parser$load_repo.invoke(git_parser.clj:56) ~[acha-uber-0.2.5.jar:na]
        at acha.dispatcher$analyze.invoke(dispatcher.clj:115) ~[acha-uber-0.2.5.jar:na]
        at acha.dispatcher$worker$fn__7644$fn__7645.invoke(dispatcher.clj:130) ~[acha-uber-0.2.5.jar:na]
        at acha.dispatcher$worker$fn__7644.invoke(dispatcher.clj:128) [acha-uber-0.2.5.jar:na]
        at acha.dispatcher$worker.invoke(dispatcher.clj:126) [acha-uber-0.2.5.jar:na]
        at acha.dispatcher$run_workers$fn__7662.invoke(dispatcher.clj:143) [acha-uber-0.2.5.jar:na]
        at clojure.lang.AFn.run(AFn.java:22) [acha-uber-0.2.5.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
Caused by: org.eclipse.jgit.errors.TransportException: git@bitbucket.org:apstrktr/leblon.git: USERAUTH fail
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159) ~[acha-uber-0.2.5.jar:na]
        at acha.git_parser.proxy$org.eclipse.jgit.transport.JschConfigSessionFactory$ff19274a.getSession(Unknown Source) ~[acha-uber-0.2.5.j$r:na]
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1115) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130) ~[acha-uber-0.2.5.jar:na]
        ... 11 common frames omitted
Caused by: com.jcraft.jsch.JSchException: USERAUTH fail
        at com.jcraft.jsch.UserAuthPublicKey.start(UserAuthPublicKey.java:118) ~[acha-uber-0.2.5.jar:na]
        at com.jcraft.jsch.Session.connect(Session.java:463) ~[acha-uber-0.2.5.jar:na]
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116) ~[acha-uber-0.2.5.jar:na]
        ... 19 common frames omitted
```

**Comment by avasenin** [comment]
Could you confirm that your repository is private on bitbucket and you have access to this repo with your default ssh keys (~/.ssh/id_rsa) but acha-acha doesn't fetch it when you add git@ URI to it?

**Comment by kishanov** [comment]
That's correct.

**Comment by avasenin** [comment]
I can't reproduce the problem. I've added my private repo to acha-acha.co successfully  (git@bitbucket.org:avasenin/ai-challenge.git on acha-acha.co).

You should use your git@ URI. Your default ssh keys should have access to this repo. If you use special keys you should specify your private key in --private-key option.

btw in start message you said that you specify id_rsa.pub in --private-key option. It's a public key. You should specify your private key.

**Comment by avasenin** [comment]
We haven't heard anything anything from you for the last week. Please reopen this issue if you still have problems with cloning private repos
